#!/usr/bin/env python3
"""Convert Bazel BEP and audit logs into a SLSA provenance document.

This script either consumes the JSON output from the Rust `bep_to_slsa` tool or
parses a BEP file directly. Audit logs from the LLVM and MLIR analyzers are
attached to the resulting provenance document under
`predicate.metadata.auditLogs`.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Any, List


def load_audit_logs(paths: List[Path]) -> Dict[str, str]:
    """Return a mapping of audit log file name to contents."""
    logs: Dict[str, str] = {}
    for path in paths:
        try:
            logs[path.name] = path.read_text()
        except OSError as exc:
            raise RuntimeError(f"Failed to read audit log {path}: {exc}") from exc
    return logs


def parse_bep(bep_data: Dict[str, Any]) -> Dict[str, Any]:
    """Parse a subset of BEP JSON into a SLSA provenance skeleton."""
    build_id = bep_data.get("id", "unknown")
    artifacts = []
    for event in bep_data.get("events", []):
        action = event.get("action", {})
        completed = action.get("completed", {})
        for output in completed.get("outputs", []):
            name = output.get("name")
            digest = output.get("digest")
            if name and digest:
                artifacts.append({
                    "name": name,
                    "digest": {"sha256": digest.replace("sha256:", "")},
                })

    slsa: Dict[str, Any] = {
        "_type": "https://slsa.dev/provenance/v0.2",
        "subject": artifacts,
        "predicate": {
            "builder": {"id": "https://github.com/agshipley/NLSAFE"},
            "buildType": "https://bazel.build/bep",
            "invocation": {
                "configSource": {
                    "uri": "git",
                    "digest": {"sha256": "UNKNOWN"},
                    "entryPoint": "WORKSPACE",
                },
                "parameters": bep_data.get("command_line", {}),
                "environment": {},
            },
            "buildConfig": bep_data.get("build_config", {}),
            "materials": [],
            "metadata": {
                "buildInvocationID": build_id,
            },
        },
    }
    return slsa


def transform_to_slsa(bep_path: Path, audit_paths: List[Path], slsa_input: Path | None) -> Dict[str, Any]:
    """Generate a SLSA document from BEP and audit logs."""
    if slsa_input:
        try:
            slsa = json.loads(slsa_input.read_text())
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"Invalid SLSA JSON in {slsa_input}: {exc}") from exc
    else:
        try:
            bep_json = json.loads(bep_path.read_text())
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"Invalid BEP JSON in {bep_path}: {exc}") from exc
        slsa = parse_bep(bep_json)

    slsa.setdefault("predicate", {}).setdefault("metadata", {})[
        "auditLogs"
    ] = load_audit_logs(audit_paths)
    return slsa


def main(argv: List[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Transform Bazel BEP and audit logs to SLSA JSON")
    parser.add_argument("--bep", type=Path, required=True, help="Path to Bazel BEP JSON file")
    parser.add_argument("--audit", type=Path, nargs="+", required=True, help="Audit log file(s) to include")
    parser.add_argument(
        "--bep-to-slsa-output",
        type=Path,
        help="Existing SLSA JSON generated by the bep_to_slsa tool",
    )
    parser.add_argument("--output", type=Path, required=True, help="Destination for provenance JSON")
    args = parser.parse_args(argv)

    slsa = transform_to_slsa(args.bep, args.audit, args.bep_to_slsa_output)

    try:
        args.output.write_text(json.dumps(slsa, indent=2))
    except OSError as exc:
        raise RuntimeError(f"Failed to write {args.output}: {exc}") from exc

    print(f"SLSA provenance written to {args.output}")


if __name__ == "__main__":  # pragma: no cover
    main()
